spring:
  datasource:
    url: jdbc:mysql://localhost:3306/serverTest?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 8556rjsdn

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

application:
  jwt:
    secretKey: 25432A462D4A614E645267556A586E3272357538782F413F4428472B4B625065
    token:
      access-expiration-time: 43200000
      refresh-expiration-time: 604800000


